module.exports = {
  q: [
	'N1_Ans',
	'N2_Ans',
	'N4_Ans',
	'N5_Ans',
	'N7_Ans',
	'N8_TempOrLong',
	'N9_Ans',
	'N10_Ans',
	'N11_Ans',
	'N12_Ans',
	'N13_Ans',
	'N14_Ans',
	'N15_Ans',
	'N16_Ans',
	'N17_Ans',
	'N18_Ans',
	'N19_Ans',
	'N20_Ans',
	'N21_Ans',
	'N22_Ans',
	'N23_Ans',
	'N24_Ans',
	'N25_Ans',
	'N26_Ans',
	'N27_Ans',
	'N28_Ans',
	'N29_Ans',
	'N30_Ans'
	
	],
  a: {
	 "N1_Ans": "HDB's season parking is intended for long term parking at HDB car parks. It allows a motorist to park at a particular HDB car park group at any time without having to display parking coupons.",
	 "N2_Ans": "HDB’s season parking is provided on a monthly basis, as it is intended for long term parking at HDB car parks. When you buy a season parking ticket, you are buying it for a calendar month, i.e. from the first to the last day of the month.<br/><br/>You may purchase or renew your season parking ticket up to 12 months in advance.",
	 "N4_Ans": 'HDB’s season parking is provided on a monthly basis, as it is intended for long term parking at HDB car parks. When you buy a season parking ticket, you are buying it for a calendar month, i.e. from the first to the last day of the month.<br/><br/>You may purchase or renew your season parking ticket up to see whether you are eligible for season parking and check the availability of the parking location, please go to our <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22CpkVcncy/BN22SeasonParkInfoSearch.jsp"> Season Parking Information e-Service</a>. You can buy your season parking ticket at <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eApplication/BN22PApplicationTerms.jsp">New Application of Season Parking Ticket</a> or renew your existing Season Parking ticket at <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22ERENEW/BN22PRenewTerms.jsp">Renewal of Season Parking Ticket</a>.',
	 "N5_Ans": 'Should you have bought a season parking ticket, you may check the validity of your season parking with our <a target="_blank" href="https://services2-pre.hdb.gov.sg/webapp/BN22PPORTALWeb/BN22VIEWLISTNVG">e-Service</a>.',
	 "N7_Ans": "We need your IU number when you apply for new season parking, a transfer or temporary season parking, if your season parking ticket's parking location is implemented with the Electronic Parking System. If you get a prompt asking you to enter the IU number, it means we have no record of it.",
	 "N8_TempOrLong": { choice: { question: "If you want to make a season parking transfer, would it be temporary or permanent?", options: { "Temporary": 'N8_DiffPark',"Long-Term": 'N8_SameOrDiffPark'}} },
	 "N8_DiffPark": 'When there is a permanent change to another parking location you can request a permanent season parking transfer through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTransfer/BN22TransferNavigation.jsp">Transfer of Car Park</a>. Transfer approval is subject to eligibility and parking space availability. Charges may apply.',
	 "N8_DiffType": 'You can request to transfer your season parking when there is a permanent change to another type of vehicle through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTransfer/BN22TransferNavigation.jsp">Transfer of Car Park</a>. Transfer application approval is subject to eligibility and parking space availability. Charges may apply.',
	 "N8_GoTempSP": 'A Temporary Transfer of Season Parking is only issued for a short period of time and is valid for a maximum of 31 days. You may apply through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTemporary/BN22TemporaryNavigation.jsp">Temporary Season Parking</a>.',
	 "N8_SameOrDiffPark": { choice: { question: "Would the transfer be to the same car park or a different one?", options: { "Same": 'N8_SameOrDiffType',"Different": 'N8_DiffPark'}} },
	 "N8_SameOrDiffType" : {  choice: { question: "Is the transfer to a similar vehicle type or something different?", options: { "Same": 'N8_SameType',"Different": 'N8_DiffType' }} },
	 "N8_SameType": 'You can request to transfer your season parking when there is a permanent change to another similar vehicle type (i.e. car to car) through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTransfer/BN22TransferNavigation.jsp">Transfer of Vehicle</a> .',
	 "N9_Ans": 'You can request a transfer of your season parking when there is a permanent change to another similar vehicle type (i.e. car to car) through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTransfer/BN22TransferNavigation.jsp">Transfer of Vehicle</a>.',
	 "N10_Ans": 'You can request a transfer of your season parking when there is a permanent change to another vehicle type through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTransfer/BN22TransferNavigation.jsp">Transfer of Vehicle</a>. Transfer application approval is subject to eligibility and parking space availability. Charges may apply.',
	 "N11_Ans": 'You can request a transfer of your season parking when there is a permanent change to another parking location through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTransfer/BN22TransferNavigation.jsp">Transfer of Car Park</a>. Transfer application approval is subject to eligibility and parking space availability. Charges may apply.',
	 "N12_Ans": 'You are only able to transfer your season parking from one vehicle to another vehicle, regardless of the vehicle type, once every 30 days. Similarly, you are only allowed to transfer from one parking space to another parking space once every 30 days.',
	 "N13_Ans": "Upon purchasing a new car, you will be considered a first time purchaser who is allowed to pay season parking charges for the applicable remaining portion of the current month on a pro-rated basis, plus a full Season Parking Ticket (SPT) payment for the following month. Please note that termination of the part of the month that's unexpired plus the next month's SPT is not permitted. For example: If you buy a car on June 21st and apply for season parking, you will have to pay season parking charges for the last 10 days of June and the whole month of July. This ticket cannot then be terminated before the end of July.",
	 "N14_Ans": 'To see whether you are eligible for season parking and check the availability of the parking location, please go to our <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22CpkVcncy/BN22SeasonParkInfoSearch.jsp">Season Parking Information e-Service</a>. You can buy your season parking ticket at <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eApplication/BN22PApplicationTerms.jsp">New Application of Season Parking Ticket</a> or renew your existing Season Parking ticket at <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22ERENEW/BN22PRenewTerms.jsp">Renewal of Season Parking Ticket</a>.',
	 "N15_Ans": 'HDB car parks are provided primarily to serve the parking needs of HDB residents. With the increased demand for parking, HDB needs to prioritise parking allocation for a fair distribution of parking spaces among residents. You may refer to <a target="_blank" href="http://www.hdb.gov.sg/cs/infoweb/car-parks/season-parking/season-parking-ticket/application-procedure">Application Procedure</a> for the various priority groups and corresponding booking dates for car parks with low and high occupancy rates. Allocation is subject to the availability of parking spaces at the designated car park at the time of purchase.',
	 "N16_Ans": 'You can renew your season parking various ways:<ol><li>Through Inter-Bank GIRO scheme by printing the <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22ISPSWeb/giroPayment/BN221GiroTerms.jsp">Online GIRO Application Form</a>, complete it and mail to us.</li><li>Through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22ERENEW/BN22PRenewTerms.jsp">Renewal of Season Parking</a>.</li><li>AXS payment channels (Station, e- Station & m-Station).</li></ol>Please note that GIRO option would take an estimated 2 weeks of processing time, subject to approval upon receiving your application.',
	 "N17_Ans": 'The length of time for which you can renew your season parking depends on the priority group and car park demand. The maximum renewal period is 12 months, subject to eligibility and availability of parking lots. You can renew your season parking through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22ERENEW/BN22PRenewTerms.jsp">Renewal of Season Parking</a>.',
	 "N18_Ans": 'Season parking renewal dates vary. For all priority groups in low occupancy car parks, the booking period starts from the 1st of the month for e-modes of payment and the 11th of the month for all modes of payment. For high occupancy car parks, HDB will prioritise the allocation of parking spaces and there will be different booking dates for different priority groups.<br/><br/>Would you like to check the renewal dates for a particular parking location?',
	 "N19_Ans": "HDB's season parking is intended for your long term parking at HDB car parks. Season parking renewal is on a calendar month basis (i.e. from the 1st to the end of the month). The season parking will take effect on the 1st day of the calendar month or on the date it is renewed, whichever is later.",
	 "N20_Ans": 'For refunds of unused Season Parking Tickets, you may terminate the ticket before the expiry date and request a refund of unexpired season parking charges. However, for termination of pro-rated tickets, refund is not allowed for the pro-rated and the immediate following month.<br/><br/>You can submit your request through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTermination/BN22PTerminationTerms.jsp">Termination of Season Parking</a>.',
	 "N21_Ans": 'Termination of pro-rated tickets is not permitted. For subsequent months, you may terminate the season parking before the expiry date and request a refund of unexpired season parking charges through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTermination/BN22PTerminationTerms.jsp">Termination of Season Parking</a>.',
	 "N22_Ans": "If you are not using your parking space, you can terminate your season parking before the expiry date and obtain a refund for unexpired season parking charges you aren't going to use.  However, no backdated refund is allowed: any request for a refund must be made prior to the dates in question. Also, it is not possible to refund a Season Parking Ticket (SPT) for the pro-rated month and the immediate following month." + '<br/><br/>You can submit your request through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTermination/BN22PTerminationTerms.jsp">Termination of Season Parking</a>. Your application will take effect immediately upon successful submission.',
	 "N23_Ans": 'Sorry that we are unable to accept any backdated refund requests. Any request for a refund must be made in advance i.e. before the period of refund.',
	 "N24_Ans": "The refund of unexpired season parking charges is computed based on the day following the date of termination. For example, if a motorist requests his or her refund on the 20th of the month, the refund will be computed effective from the 21st up to the ticket's expiry date.",
	 "N25_Ans": 'The way your refund is paid out depends on the form of payment you used. If your season parking was paid via GIRO, we will refund the bank account directly, and you will not need to furnish any banking information. Non-GIRO season parking motorists will need to provide us with bank account details so we can process the refund.',
	 "N26_Ans": 'A temporary Season Parking Ticket is only issued for a short period of time. It is not intended for long term or frequent use, and lasts a maximum of 31 days. You may apply through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTemporary/BN22TemporaryNavigation.jsp">Temporary Season Parking</a>.',
	 "N27_Ans": 'A temporary Season Parking Ticket is only issued for a short period of time. It is not intended for long term or frequent use, and lasts a maximum of 31 days. You may apply through <a target="_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTemporary/BN22TemporaryNavigation.jsp">Temporary Season Parking</a>.',
	 "N28_Ans": 'To  answer your question about requesting a temporary parking ticket, I need to know a bit more. Is there any vehicle change?',
	 "N29_Ans": 'You can request temporary season parking for your temporary vehicle of a similar vehicle type (e.g. car to car) through <a target=\\_blank" href="https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTemporary/BN22TemporaryNavigation.jsp">Temporary Change of Vehicle</a>.',
	 "N30_Ans": 'You can apply for temporary season parking at a different car park. For SPT holders who require parking at another car park temporarily, you may apply for temporary season parking at another car park through <a target=\\_blank\\" href=\\"https://services2.hdb.gov.sg/webapp/BN22PPORTALWeb/eTemporary/BN22TemporaryNavigation.jsp\\">Temporary Change of Car Park</a>.',
	 "N31_Ans": 'No supporting document is required at the point of application. However, HDB may contact you for the documents for verification, if necessary.',
	 "N32_Ans": 'Temporary season parking at another car park is limited to 3 times within 6 months.',
	 "N33_Ans": 'There are no refunds for any unused portion of a temporary Season Parking Ticket.',
	 "N34_Ans": 'There is no administrative fee for Temporary Season Parking.',
	 "N35_Ans": 'To answer your question, I need a bit more information. Are you changing vehicles?',
	}
};

